Vagrant.configure("2") do |config|
  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "ubuntu/xenial64"
    ubuntu.vm.hostname = "docker-ubuntu"
    ubuntu.vm.synced_folder ".", "/vagrant", disabled: true
    ubuntu.vm.provision :shell, :inline => "ulimit -n 4096"
    ubuntu.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "centos/7"
    centos.vm.hostname = "docker-centos"
    centos.vm.synced_folder ".", "/vagrant", disabled: true
    centos.vm.provision :shell, :inline => "ulimit -n 4096"
    centos.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end
end
