#!/usr/bin/env bash
set -x

# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.

# Available environment variables
#
# NEXUS_ARTIFACT_REPOSITORY
# NEXUS_ARTIFACT_NAME
# NEXUS_USERNAME
# NEXUS_PASSWORD
# NEXUS_SERVER
#
# NEXUSFILE

# Set default values

NEXUSFILE=${NEXUSFILE:-nexus}
if [[ -e $NEXUSFILE ]]; then
    source $NEXUSFILE
fi

HASH=$(git rev-parse --short HEAD)
ARCHIVE=$NEXUS_ARTIFACT_NAME-$HASH.tar.gz

if [[ ! -z $(git tag | grep $HASH) ]]; then
    exit 0
fi

# Remove molecule.yml vars file

rm -f vars/molecule.yml

# Prepare tarball

tar cvzf $ARCHIVE $(ls -d README.md defaults files handlers meta tasks templates vars 2>/dev/null)
mkdir $NEXUS_ARTIFACT_NAME
tar xvzf $ARCHIVE -C $NEXUS_ARTIFACT_NAME
tar cvzf $ARCHIVE $NEXUS_ARTIFACT_NAME

# Push tarball to nexus server

curl -v --user "$NEXUS_USERNAME:$NEXUS_PASSWORD" --upload-file $ARCHIVE https://$NEXUS_SERVER/repository/$NEXUS_ARTIFACT_REPOSITORY/$ARCHIVE
curl -v --user "$NEXUS_USERNAME:$NEXUS_PASSWORD" --upload-file $ARCHIVE https://$NEXUS_SERVER/repository/$NEXUS_ARTIFACT_REPOSITORY/$NEXUS_ARTIFACT_NAME-latest.tar.gz

# Cleanup

rm -f $ARCHIVE
rm -rf $NEXUS_ARTIFACT_NAME
