#!/usr/bin/env bash

# DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN

# This file is subject to the terms and conditions defined in file 'LICENSE',
# which is part of this repository.

# Available environment variables
#
# ANSIBLEVERSION
# DOCKERFILE
# MOLECULEVARSFILE
# OPENRCFILE

# Set default values

OPENRCFILE=${OPENRCFILE:-openrc}
if [[ -e $OPENRCFILE ]]; then
    source $OPENRCFILE
fi

if [[ -e $DOCKERFILE ]]; then
    source $DOCKERFILE
fi

if [[ -e $MOLECULEVARSFILE ]]; then
    cp $MOLECULEVARSFILE vars/molecule.yml
fi

if [[ -e tox.ini ]]; then
    tox -e ansible$ANSIBLEVERSION
fi
